# DC schema
 
# --- !Ups

DROP TABLE IF EXISTS CLUBS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE CLUBS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SHORTCUT VARCHAR(20)
);

CREATE TABLE USERS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CLUB_ID INT NOT NULL,
    foreign key (CLUB_ID) references CLUBS(ID)
);

-- INSERT INTO CLUBS VALUES (0,'Visma Coding Club','VCC');
-- INSERT INTO USERS VALUES (0,'Simo', 0);

# --- !Downs

DROP TABLE Clubs;
DROP TABLE USERS
